import { mkdirSync, writeFileSync } from "node:fs";
import { createClient } from "@supabase/supabase-js";
import { parseArgs, resolveSupabaseTarget } from "./target.mjs";

const args = parseArgs();
const target = await resolveSupabaseTarget(args);
const client = createClient(target.url, target.serviceRoleKey, {
  auth: {
    autoRefreshToken: false,
    persistSession: false,
  },
});

const [
  runners,
  legDefinitions,
  placements,
  results,
  raceParticipations,
] = await Promise.all([
  fetchAll("runners", "id,name,email", "name"),
  fetchAll("leg_definitions", "number,version,distance,elevation_gain", "number"),
  fetchAll(
    "placements",
    "year,division,division_place,division_teams,overall_place,overall_teams,bib,notes",
    "year"
  ),
  fetchAll("results", "year,leg_number,leg_version,lap_time,user_id,notes", "year"),
  fetchAll("race_participations", "year,runner_id,status,notes", "year"),
]);

const runnerById = new Map(runners.map((runner) => [runner.id, runner]));

assertUniqueRunnerNames(runners);
assertKnownRunnerReferences(results, "user_id", runnerById, "results");
assertKnownRunnerReferences(raceParticipations, "runner_id", runnerById, "race_participations");

const seedSql = renderSeedSql({
  generatedAt: new Date().toISOString(),
  target,
  runners,
  legDefinitions,
  placements,
  results,
  raceParticipations,
  runnerById,
});

writeFileSync("supabase/seed.sql", seedSql);
console.log(`Wrote supabase/seed.sql from ${target.mode} (${target.projectRef}).`);

if (args.backup) {
  const backup = {
    generatedAt: new Date().toISOString(),
    target: {
      mode: target.mode,
      projectRef: target.projectRef,
      url: target.url,
    },
    public: {
      runners,
      legDefinitions,
      placements,
      results,
      raceParticipations,
    },
    authUsers: await listRunnerAuthUsers(client),
  };
  const timestamp = backup.generatedAt.replace(/[:.]/g, "-");
  const backupDir = ".backups/supabase";
  const backupPath = `${backupDir}/${target.mode}-${target.projectRef}-${timestamp}.json`;

  mkdirSync(backupDir, { recursive: true });
  writeFileSync(backupPath, `${JSON.stringify(backup, null, 2)}\n`);
  console.log(`Wrote private backup ${backupPath}.`);
}

async function fetchAll(table, columns, orderColumn) {
  const pageSize = 1000;
  const rows = [];

  for (let from = 0; ; from += pageSize) {
    const to = from + pageSize - 1;
    const { data, error } = await client
      .from(table)
      .select(columns)
      .order(orderColumn, { ascending: true })
      .range(from, to);

    if (error) {
      throw new Error(`Failed fetching ${table}: ${error.message}`);
    }

    rows.push(...(data || []));

    if (!data || data.length < pageSize) {
      break;
    }
  }

  return rows;
}

async function listRunnerAuthUsers(adminClient) {
  const runnerEmails = new Set(
    runners
      .map((runner) => normalizeEmail(runner.email))
      .filter(Boolean)
  );
  const authUsers = [];
  let page = 1;

  while (true) {
    const { data, error } = await adminClient.auth.admin.listUsers({
      page,
      perPage: 1000,
    });

    if (error) {
      throw error;
    }

    for (const user of data.users || []) {
      const email = normalizeEmail(user.email);

      if (runnerEmails.has(email)) {
        authUsers.push({
          id: user.id,
          email,
          created_at: user.created_at,
          confirmed_at: user.confirmed_at,
          email_confirmed_at: user.email_confirmed_at,
          last_sign_in_at: user.last_sign_in_at,
        });
      }
    }

    if (!data.users || data.users.length < 1000) {
      break;
    }

    page += 1;
  }

  return authUsers.sort((a, b) => a.email.localeCompare(b.email));
}

function renderSeedSql({
  generatedAt,
  target,
  runners,
  legDefinitions,
  placements,
  results,
  raceParticipations,
  runnerById,
}) {
  const lines = [
    "-- Generated by scripts/supabase/export-seed.mjs.",
    `-- Source: ${target.mode} (${target.projectRef}) at ${generatedAt}.`,
    "-- Auth users are intentionally excluded; run npm run db:auth:ensure:local after db reset.",
    "",
    "BEGIN;",
    "",
    "TRUNCATE TABLE",
    "  public.race_participations,",
    "  public.results,",
    "  public.placements,",
    "  public.leg_definitions,",
    "  public.runners",
    "RESTART IDENTITY CASCADE;",
    "",
    renderValuesInsert(
      "public.runners",
      ["email", "name"],
      runners.map((runner) => [normalizeEmail(runner.email) || null, runner.name])
    ),
    "",
    renderValuesInsert(
      "public.leg_definitions",
      ["number", "version", "distance", "elevation_gain"],
      legDefinitions
        .slice()
        .sort((a, b) => a.number - b.number || a.version - b.version)
        .map((leg) => [leg.number, leg.version, leg.distance, leg.elevation_gain])
    ),
    "",
    renderValuesInsert(
      "public.placements",
      [
        "year",
        "division",
        "division_place",
        "division_teams",
        "overall_place",
        "overall_teams",
        "bib",
        "notes",
      ],
      placements
        .slice()
        .sort((a, b) => a.year - b.year)
        .map((placement) => [
          placement.year,
          placement.division,
          placement.division_place,
          placement.division_teams,
          placement.overall_place,
          placement.overall_teams,
          placement.bib,
          placement.notes,
        ])
    ),
    "",
    renderResultsInsert(results, runnerById),
    "",
    renderRaceParticipationsInsert(raceParticipations, runnerById),
    "",
    "COMMIT;",
    "",
  ];

  return lines.join("\n");
}

function renderValuesInsert(table, columns, rows) {
  if (rows.length === 0) {
    return `-- No rows for ${table}.`;
  }

  return [
    `INSERT INTO ${table} (${columns.join(", ")}) VALUES`,
    rows.map((row) => `  (${row.map(sqlValue).join(", ")})`).join(",\n") + ";",
  ].join("\n");
}

function renderResultsInsert(results, runnerById) {
  if (results.length === 0) {
    return "-- No rows for public.results.";
  }

  const rows = results
    .slice()
    .sort((a, b) => a.year - b.year || a.leg_number - b.leg_number)
    .map((result) => {
      const runner = result.user_id ? runnerById.get(result.user_id) : null;
      const runnerRef = runner
        ? `(SELECT id FROM public.runners WHERE name = ${sqlValue(runner.name)})`
        : "NULL";

      return [
        result.year,
        result.leg_number,
        result.leg_version,
        runnerRef,
        sqlInterval(result.lap_time),
        sqlValue(result.notes),
      ];
    });

  return [
    "INSERT INTO public.results (year, leg_number, leg_version, user_id, lap_time, notes) VALUES",
    rows
      .map(([year, legNumber, legVersion, runnerRef, lapTime, notes]) =>
        `  (${year}, ${legNumber}, ${legVersion}, ${runnerRef}, ${lapTime}, ${notes})`
      )
      .join(",\n") + ";",
  ].join("\n");
}

function renderRaceParticipationsInsert(raceParticipations, runnerById) {
  if (raceParticipations.length === 0) {
    return "-- No rows for public.race_participations.";
  }

  const rows = raceParticipations
    .slice()
    .sort((a, b) => {
      const runnerA = runnerById.get(a.runner_id)?.name || "";
      const runnerB = runnerById.get(b.runner_id)?.name || "";
      return a.year - b.year || runnerA.localeCompare(runnerB);
    })
    .map((participation) => {
      const runner = runnerById.get(participation.runner_id);

      return [
        participation.year,
        runner.name,
        participation.status,
        participation.notes,
      ];
    });

  return [
    "INSERT INTO public.race_participations (year, runner_id, status, notes)",
    "SELECT seed.year, runners.id, seed.status, seed.notes",
    "FROM (VALUES",
    rows
      .map((row) => `  (${row.map(sqlValue).join(", ")})`)
      .join(",\n"),
    ") AS seed(year, runner_name, status, notes)",
    "JOIN public.runners ON public.runners.name = seed.runner_name",
    "ON CONFLICT (year, runner_id) DO UPDATE",
    "SET status = EXCLUDED.status,",
    "    notes = EXCLUDED.notes,",
    "    updated_at = now();",
  ].join("\n");
}

function assertUniqueRunnerNames(runners) {
  const seen = new Set();

  for (const runner of runners) {
    if (seen.has(runner.name)) {
      throw new Error(`Cannot generate seed with duplicate runner name: ${runner.name}`);
    }

    seen.add(runner.name);
  }
}

function assertKnownRunnerReferences(rows, key, runnerById, table) {
  for (const row of rows) {
    if (row[key] && !runnerById.has(row[key])) {
      throw new Error(`${table} references unknown runner id ${row[key]}`);
    }
  }
}

function normalizeEmail(email) {
  return String(email || "").trim().toLowerCase();
}

function sqlValue(value) {
  if (value === null || value === undefined || value === "") {
    return "NULL";
  }

  if (typeof value === "number") {
    return Number.isFinite(value) ? String(value) : "NULL";
  }

  return `'${String(value).replaceAll("'", "''")}'`;
}

function sqlInterval(value) {
  if (value === null || value === undefined || value === "") {
    return "NULL";
  }

  return `INTERVAL ${sqlValue(value)}`;
}
